export const LAPTOPER_FETCH_START = 'LAPTOPER_FETCH_START'
export const LAPTOPER_FETCH_DONE = 'LAPTOPER_FETCH_DONE'
export const LAPTOPER_FETCH_FAIL = 'LAPTOPER_FETCH_FAIL'

export const DEPARTMENT_FETCH_START = 'DEPARTMENT_FETCH_START'
export const DEPARTMENT_FETCH_DONE = 'DEPARTMENT_FETCH_DONE'
export const DEPARTMENT_FETCH_FAIL = 'DEPARTMENT_ETCH_FAIL'

export const PRODUCTS_FETCH_START = 'PRODUCTS_FETCH_START'
export const PRODUCTS_FETCH_DONE = 'PRODUCTS_FETCH_DONE'
export const PRODUCTS_FETCH_FAIL = 'PRODUCTS_ETCH_FAIL'

// export const CATAGORY_FETCH_START = 'CATAGORY_FETCH_START'
// export const CATAGORY_FETCH_DONE = 'CATAGORY_FETCH_DONE'
// export const CATAGORY_FETCH_FAIL = 'CATAGORY_ETCH_FAIL'

// export const SUBCATAGORY_FETCH_START = 'SUBCATAGORY_FETCH_START'
// export const SUBCATAGORY_FETCH_DONE = 'SUBCATAGORY_FETCH_DONE'
// export const SUBCATAGORY_FETCH_FAIL = 'SUBCATAGORY_ETCH_FAIL'

export const POPULAR = 'POPULAR'
export const LATEST = 'LATEST'
export const RECOMEND = 'RECOMEND'

export const SET_VIEW = 'SET_VIEW'
export const HANDLE_CART = 'HANDLE_CART'
export const HANDLE_REVIEW = 'HANDLE_REVIEW'
export const HANDLE_EDIT = 'HANDLE_EDIT'



export const PRODUCTS = 'PRODUCTS'

export const CATALOG = 'CATALOG'
export const CATAGORYS = 'CATAGORYS'
export const CATAGORY = 'CATAGORY'

export const PROMOS_FETCH_START = 'PROMOS_FETCH_START'
export const PROMOS_FETCH_DONE = 'PROMOS_FETCH_DONE'
export const PROMOS_FETCH_FAIL = 'PROMOS_FETCH_FAIL'
export const PROMO_FETCH_START = 'PROMO_FETCH_START'
export const PROMO_FETCH_DONE = 'PROMO_FETCH_DONE'
export const PROMO_FETCH_FAIL = 'PROMO_FETCH_FAIL'

export const BLOG_FETCH_START = 'BLOG_FETCH_START'
export const BLOG_FETCH_DONE = 'BLOG_FETCH_DONE'
export const BLOG_FETCH_FAIL = 'BLOG_ETCH_FAIL'

export const POST_FETCH_START = 'POST_FETCH_START'
export const POST_FETCH_DONE = 'POST_FETCH_DONE'
export const POST_FETCH_FAIL = 'POST_ETCH_FAIL'


export const PRODUCT = 'PRODUCT'
export const COMMENTS = 'COMMENTS'

export const CART = 'CART'

export const SIGNUP_START = 'SIGNUP_START'
export const SIGNUP_DONE = 'SIGNUP_DONE'
export const SIGNUP_FAIL = 'SIGNUP_FAIL'

export const AUTH_DONE = 'AUTH_DONE'
export const AUTH_FAIL = 'AUTH_FAIL'

export const USER_FETCH_START = 'USER_FETCH_START'
export const USER_FETCH_DONE = 'USER_FETCH_DONE'
export const USER_FETCH_FAIL = 'USER_FETCH_FAIL'

export const USER_ORDERS_FETCH_START = 'USER_ORDERS_FETCH_START'
export const USER_ORDERS_FETCH_DONE = 'USER_ORDERS_FETCH_DONE'
export const USER_ORDERS_FETCH_FAIL = 'USER_ORDERS_FETCH_FAIL'

export const USER_HISTORY_FETCH_START = 'USER_HISTORY_FETCH_START'
export const USER_HISTORY_FETCH_DONE = 'USER_HISTORY_FETCH_DONE'
export const USER_HISTORY_FETCH_FAIL = 'USER_HISTORY_FETCH_FAIL'

export const LIST_FETCH_START = 'LIST_FETCH_START'
export const LIST_FETCH_DONE = 'LIST_FETCH_DONE'
export const LIST_FETCH_FAIL = 'LIST_ETCH_FAIL'
export const LIST_SELECT = 'LIST_SELECT'

export const USER_COMMENTS = 'USER_COMMENTS'
export const COMPARE = 'COMPARE'
export const DESIRES_LISTS = 'DESIRES_LISTS'
